Avoid core dump on cli exception (#258)
Avoid this:

```
root@c010-0202:/# ./external/com_github_agtonomy_trellis/trellis/tools/trellis-cli/trellis-cli topic echo -t /commander/state -c 1
terminate called after throwing an instance of 'cxxopts::option_not_exists_exception'
  what():  Option ‘c’ does not exist
Aborted (core dumped)
```

New output:

```
$ trellis-cli topic echo -t /x --bogus
error: Option 'bogus' does not exist
```

We still core dump so you get a trace on unknown exceptions.